export enum ForgotPassErrors {
  EMAIL_NOT_REGISTERED = 'EMAIL_NOT_REGISTERED',
  SEND_EMAIL_ERROR = 'SEND_EMAIL_ERROR',
  VERIFICATION_CODE_INVALID = 'VERIFICATION_CODE_INVALID',
  ALREADY_IN_PROGRESS = 'ALREADY_IN_PROGRESS',
  SERVER_INTERNAL_ERROR = 'SERVER_INTERNAL_ERROR',
}
