export enum InviteUserErrorsDto {
  USER_ALREADY_INVITED = 'USER_ALREADY_INVITED',
  INVALID_EMAIL_FORMAT = 'INVALID_EMAIL_FORMAT',
  INVITE_LIMIT_EXCEEDED = 'INVITE_LIMIT_EXCEEDED',
  ORGANIZATION_NOT_FOUND = 'ORGANIZATION_NOT_FOUND',
  USER_ALREADY_REGISTERED = 'USER_ALREADY_REGISTERED',
  ORGANIZATION_NOT_VALID = 'ORGANIZATION_NOT_VALID',
  ERROR_SENDING_EMAIL = 'ERROR_SENDING_EMAIL',
  ERROR_CREATING_RECORD = 'ERROR_CREATING_RECORD',
}
