export enum EventSubjectType {
  API_KEY = 'ApiKey',
  AUDIT_LOG = 'AuditLog',
  CONVERSATION = 'Conversation',
  CREDIT_BALANCE = 'CreditBalance',
  CREDIT_TRANSACTION = 'CreditTransaction',
  END_USER = 'EndUser',
  EXECUTION = 'Execution',
  INVOICE = 'Invoice',
  LLM_MODEL = 'LlmModel',
  MESSAGE = 'Message',
  ORGANIZATION = 'Organization',
  REFRESH_TOKEN = 'RefreshToken',
  SUBSCRIPTION = 'Subscription',
  TAG = 'Tag',
  TENANT_TOOL = 'TenantTool',
  TENANT_CATALOG = 'TenantCatalog',
  TOOL_FUNCTION = 'ToolFunction',
  USER = 'User',
  USER_VERIFICATION = 'UserVerification',
  WHATSAPP_CONFIG = 'WhatsAppConfig',
  WORKFLOW = 'Workflow',
  USER_NOTIFICATION = 'UserNotification',
}
