name: Sync to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to personal repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        with:
          source-directory: '.'
          destination-github-username: 'DannyyLC'
          destination-repository-name: 'Tesseract-Web'
          target-branch: main
          user-email: cervantesdaniellimon50m@gmail.com
